sudo: required
conditions: v1
language: java
jdk:
  - openjdk8
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
jobs:
  include:
    # run unit tests and build
    - stage: test
      name: tests
      script:
        - ./gradlew test shadowJar
        - ./gradlew jacocoTestReport

    # deploy only if on one of the main branches
    # - master is the latest public/live/production version
    # - staging is the next stable public/live/production version
    # - develop is the rolling development release version
    - stage: deploy-branch
      name: deploy-branch
      if: branch IN (master, staging, develop)
      script:
        - docker build -t temp .
        - docker tag temp "southclaws/tw-economy:$TRAVIS_BRANCH"
        - docker push "southclaws/tw-economy:$TRAVIS_BRANCH"
    - stage: deploy-tag
      name: deploy-tag
      if: tag IS present
      script:
        - docker build -t temp .
        - docker tag temp "southclaws/tw-economy:$TRAVIS_TAG"
        - docker push "southclaws/tw-economy:$TRAVIS_TAG"
after_success:
  - bash <(curl -s https://codecov.io/bash)